/**
 * Correctness comparison: our WASM builds vs known BLAKE3 test vectors.
 *
 * Verifies hash, keyed_hash, derive_key, streaming Hasher, and stream
 * convenience functions all produce correct output. Test vectors are
 * generated by native blake3 via blake3_debug.
 *
 * Usage: deno task test:deno          (tests blake3_wasm)
 *        deno task test:deno:small    (tests blake3_wasm_small)
 *
 * Flags:
 *   --small   Test blake3_wasm_small instead of blake3_wasm
 */

import { assertEquals, assertRejects, assertThrows } from 'jsr:@std/assert';

const small_mode = Deno.args.includes('--small');
const pkg_name = small_mode ? 'blake3_wasm_small' : 'blake3_wasm';
const pkg_dir = small_mode ? 'crates/blake3_wasm_small' : 'crates/blake3_wasm';
const artifact = `${pkg_dir}/pkg/deno/${pkg_name}.js`;

try {
	Deno.statSync(new URL(`../${artifact}`, import.meta.url));
} catch {
	throw new Error(
		`WASM artifact not found: ${artifact}\n` +
			`Run 'deno task ${small_mode ? 'compare:small' : 'compare:wasm'}' to build and test,` +
			` or 'deno task build:wasm' to build all targets.`,
	);
}

const mod_path = `../${pkg_dir}/mod.ts`;

const {
	Blake3Hasher,
	derive_key,
	derive_key_stream,
	hash,
	hash_stream,
	keyed_hash,
	keyed_hash_stream,
} = await import(mod_path);

interface TestVector {
	label: string;
	input_hex: string;
	hash: string;
	keyed_hash: string;
	keyed_hash_key_hex: string;
	derive_key: string;
	derive_key_context: string;
}

const encoder = new TextEncoder();

function to_hex(bytes: Uint8Array): string {
	return Array.from(bytes)
		.map((b) => b.toString(16).padStart(2, '0'))
		.join('');
}

function hex_to_bytes(hex: string): Uint8Array {
	const bytes = new Uint8Array(hex.length / 2);
	for (let i = 0; i < hex.length; i += 2) {
		bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16);
	}
	return bytes;
}

function make_stream(data: Uint8Array): ReadableStream<Uint8Array> {
	return new ReadableStream({
		start(controller) {
			// Feed in two chunks to exercise the streaming path
			const mid = Math.floor(data.length / 2);
			if (mid > 0) controller.enqueue(data.subarray(0, mid));
			if (mid < data.length) controller.enqueue(data.subarray(mid));
			controller.close();
		},
	});
}

// Load test vectors from shared JSON (generated by: cargo run -p blake3_debug -- test-vectors)
const test_vectors: TestVector[] = JSON.parse(
	Deno.readTextFileSync(new URL('../test/test_vectors.json', import.meta.url)),
);

Deno.test(`${pkg_name}: one-shot hash`, async (t) => {
	for (const v of test_vectors) {
		const input = hex_to_bytes(v.input_hex);

		await t.step(`hash(${v.label})`, () => {
			assertEquals(to_hex(hash(input)), v.hash);
		});
	}
});

Deno.test(`${pkg_name}: keyed hash`, async (t) => {
	for (const v of test_vectors) {
		await t.step(`keyed_hash(${v.label})`, () => {
			const input = hex_to_bytes(v.input_hex);
			const key = hex_to_bytes(v.keyed_hash_key_hex);
			assertEquals(to_hex(keyed_hash(key, input)), v.keyed_hash);
		});
	}
});

Deno.test(`${pkg_name}: derive key`, async (t) => {
	for (const v of test_vectors) {
		await t.step(`derive_key(${v.label})`, () => {
			const input = hex_to_bytes(v.input_hex);
			assertEquals(to_hex(derive_key(v.derive_key_context, input)), v.derive_key);
		});
	}
});

Deno.test(`${pkg_name}: streaming hasher`, async (t) => {
	// Single-chunk streaming should match one-shot
	for (const v of test_vectors) {
		await t.step(`single-chunk(${v.label})`, () => {
			const input = hex_to_bytes(v.input_hex);
			const h = new Blake3Hasher();
			h.update(input);
			assertEquals(to_hex(h.finalize()), v.hash);
			h.free();
		});
	}

	// Multi-chunk streaming
	await t.step('multi-chunk matches one-shot', () => {
		const hello = encoder.encode('hello');
		const expected = to_hex(hash(hello));
		const h = new Blake3Hasher();
		h.update(encoder.encode('hel'));
		h.update(encoder.encode('lo'));
		assertEquals(to_hex(h.finalize()), expected);
		h.free();
	});

	// Byte-at-a-time streaming
	await t.step('byte-at-a-time matches one-shot', () => {
		const hello = encoder.encode('hello');
		const expected = to_hex(hash(hello));
		const h = new Blake3Hasher();
		for (const byte of hello) {
			h.update(new Uint8Array([byte]));
		}
		assertEquals(to_hex(h.finalize()), expected);
		h.free();
	});

	// Reset
	await t.step('reset works', () => {
		const hello = encoder.encode('hello');
		const expected = to_hex(hash(hello));
		const h = new Blake3Hasher();
		h.update(encoder.encode('garbage'));
		h.reset();
		h.update(hello);
		assertEquals(to_hex(h.finalize()), expected);
		h.free();
	});

	// Finalize is non-destructive (can call multiple times)
	await t.step('finalize is non-destructive', () => {
		const h = new Blake3Hasher();
		h.update(encoder.encode('hello'));
		const first = to_hex(h.finalize());
		const second = to_hex(h.finalize());
		assertEquals(first, second);
		h.free();
	});

	// finalize_and_reset returns same digest as finalize, then resets
	await t.step('finalize_and_reset returns digest and resets', () => {
		const hello = encoder.encode('hello');
		const hello_hash = to_hex(hash(hello));
		const h = new Blake3Hasher();
		h.update(hello);
		assertEquals(to_hex(h.finalize_and_reset()), hello_hash);
		// After reset, hashing new data should produce fresh result
		h.update(encoder.encode('world'));
		assertEquals(to_hex(h.finalize()), to_hex(hash(encoder.encode('world'))));
		h.free();
	});

	// finalize_and_reset preserves keyed mode
	await t.step('finalize_and_reset preserves keyed mode', () => {
		const key = new Uint8Array(32).fill(0x02);
		const hello = encoder.encode('hello');
		const h = Blake3Hasher.new_keyed(key);
		h.update(hello);
		assertEquals(to_hex(h.finalize_and_reset()), to_hex(keyed_hash(key, hello)));
		// After reset, keyed mode should be preserved
		const world = encoder.encode('world');
		h.update(world);
		assertEquals(to_hex(h.finalize()), to_hex(keyed_hash(key, world)));
		h.free();
	});

	// finalize_and_reset preserves derive-key mode
	await t.step('finalize_and_reset preserves derive-key mode', () => {
		const context = 'blake3-wasm-test finalize_and_reset';
		const hello = encoder.encode('hello');
		const h = Blake3Hasher.new_derive_key(context);
		h.update(hello);
		assertEquals(to_hex(h.finalize_and_reset()), to_hex(derive_key(context, hello)));
		// After reset, derive-key mode should be preserved
		const world = encoder.encode('world');
		h.update(world);
		assertEquals(to_hex(h.finalize()), to_hex(derive_key(context, world)));
		h.free();
	});

	// Keyed streaming
	await t.step('keyed streaming matches keyed one-shot', () => {
		const key = new Uint8Array(32).fill(0x01);
		const hello = encoder.encode('hello');
		const h = Blake3Hasher.new_keyed(key);
		h.update(hello);
		assertEquals(to_hex(h.finalize()), to_hex(keyed_hash(key, hello)));
		h.free();
	});

	// Derive key streaming
	await t.step('derive-key streaming matches derive-key one-shot', () => {
		const context = 'blake3-wasm-test 2024';
		const hello = encoder.encode('hello');
		const h = Blake3Hasher.new_derive_key(context);
		h.update(hello);
		assertEquals(to_hex(h.finalize()), to_hex(derive_key(context, hello)));
		h.free();
	});
});

Deno.test(`${pkg_name}: stream functions`, async (t) => {
	for (const v of test_vectors) {
		await t.step(`hash_stream(${v.label})`, async () => {
			const input = hex_to_bytes(v.input_hex);
			const result = await hash_stream(make_stream(input));
			assertEquals(to_hex(result), v.hash);
		});
	}

	for (const v of test_vectors) {
		await t.step(`keyed_hash_stream(${v.label})`, async () => {
			const input = hex_to_bytes(v.input_hex);
			const key = hex_to_bytes(v.keyed_hash_key_hex);
			const result = await keyed_hash_stream(key, make_stream(input));
			assertEquals(to_hex(result), v.keyed_hash);
		});
	}

	for (const v of test_vectors) {
		await t.step(`derive_key_stream(${v.label})`, async () => {
			const input = hex_to_bytes(v.input_hex);
			const result = await derive_key_stream(v.derive_key_context, make_stream(input));
			assertEquals(to_hex(result), v.derive_key);
		});
	}

	// Batch boundary tests — exercises all 3 code paths in hash_stream_core (BATCH_SIZE = 16384)
	await t.step('hash_stream with 32KB chunk (batch bypass)', async () => {
		// Path 1: chunk >= BATCH_SIZE → flush accumulated, pass chunk directly
		const chunk = new Uint8Array(32768).fill(0x42);
		const expected = to_hex(hash(chunk));
		const stream = new ReadableStream({
			start(c) {
				c.enqueue(chunk);
				c.close();
			},
		});
		assertEquals(to_hex(await hash_stream(stream)), expected);
	});

	await t.step('hash_stream batch overflow boundary', async () => {
		// Path 2: accumulated + chunk > BATCH_SIZE → flush, start new batch
		// 15 KB accumulated + 2 KB = 17 KB > 16 KB batch
		const small_chunks = Array.from({ length: 15 }, () => new Uint8Array(1024).fill(0xaa));
		const overflow_chunk = new Uint8Array(2048).fill(0xbb);
		const full = new Uint8Array(15 * 1024 + 2048);
		for (let i = 0; i < 15; i++) full.set(small_chunks[i], i * 1024);
		full.set(overflow_chunk, 15 * 1024);
		const expected = to_hex(hash(full));
		const stream = new ReadableStream({
			start(c) {
				for (const chunk of small_chunks) c.enqueue(chunk);
				c.enqueue(overflow_chunk);
				c.close();
			},
		});
		assertEquals(to_hex(await hash_stream(stream)), expected);
	});

	await t.step('hash_stream mixed chunk sizes (all code paths)', async () => {
		const chunks = [
			new Uint8Array(100).fill(0x01), // path 3: small, accumulate
			new Uint8Array(16384).fill(0x02), // path 1: >= BATCH_SIZE, flush + direct
			new Uint8Array(8192).fill(0x03), // path 3: accumulate
			new Uint8Array(9000).fill(0x04), // path 2: 8192+9000 > 16384, overflow
			new Uint8Array(50).fill(0x05), // path 3: small, accumulate (leftover)
		];
		const total = chunks.reduce((a, c) => a + c.length, 0);
		const full = new Uint8Array(total);
		let offset = 0;
		for (const c of chunks) {
			full.set(c, offset);
			offset += c.length;
		}
		const expected = to_hex(hash(full));
		const stream = new ReadableStream({
			start(controller) {
				for (const c of chunks) controller.enqueue(c);
				controller.close();
			},
		});
		assertEquals(to_hex(await hash_stream(stream)), expected);
	});

	await t.step('hash_stream batching (many small chunks)', async () => {
		// 128 chunks of 1KB = 128KB total, exercises batch accumulation + flush
		const chunk = new Uint8Array(1024).fill(0x42);
		const full = new Uint8Array(128 * 1024);
		for (let i = 0; i < 128; i++) full.set(chunk, i * 1024);
		const expected = to_hex(hash(full));
		const stream = new ReadableStream({
			start(controller) {
				for (let i = 0; i < 128; i++) controller.enqueue(chunk.slice());
				controller.close();
			},
		});
		assertEquals(to_hex(await hash_stream(stream)), expected);
	});
});

Deno.test(`${pkg_name}: error paths`, async (t) => {
	await t.step('keyed_hash throws on 16-byte key', () => {
		assertThrows(
			() => keyed_hash(new Uint8Array(16), new Uint8Array(0)),
			Error,
			'key must be exactly 32 bytes',
		);
	});

	await t.step('new_keyed throws on empty key', () => {
		assertThrows(
			() => Blake3Hasher.new_keyed(new Uint8Array(0)),
			Error,
			'key must be exactly 32 bytes',
		);
	});

	await t.step('new_keyed throws on 16-byte key', () => {
		assertThrows(
			() => Blake3Hasher.new_keyed(new Uint8Array(16)),
			Error,
			'key must be exactly 32 bytes',
		);
	});

	await t.step('keyed_hash_stream throws on 16-byte key', async () => {
		await assertRejects(
			() => keyed_hash_stream(new Uint8Array(16), make_stream(new Uint8Array(0))),
			Error,
			'key must be exactly 32 bytes',
		);
	});
});
